services:
  sam:
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - cache
    environment:
      - DB-HOST=cache
      - DB-PORT=6379
  cache:
    image: redis:alpine
    restart: always
    volumes:
      - cache:/data
    ports:
      - 6379:6379
volumes:
  cache:
    driver: local
